MONTH and YEAR functions
ulalka/excel-formulas-calculator pull request #4
Opened 2021-11-10 09:07 UTC by AntonArsentiev

2021-11-10 09:41 UTC, ulalka requested changes

2021-11-10 09:41 UTC, ulalka commented on efc/rpn_builder/parser/functions.py
> +                value = datetime.strptime(cell_operand.string, date_format.format(separator))
`format` method pretty slow, use `%` instead

2021-11-10 09:41 UTC, ulalka commented on efc/rpn_builder/parser/functions.py
> +            except:
`except` without an exception class handle every exception, e.g. `KeyboardInterrupt` or `SystemExit`. You should specify the exception class.

2021-11-10 09:41 UTC, ulalka commented on efc/rpn_builder/parser/functions.py
> +    for date_format in (YMD_DATE_FORMAT, DMY_DATE_FORMAT):
According to the documentation, there are correct formats:
`=MONTH("28.02.2011")`
`=MONTH("28/02/2011")`
`=MONTH("28-02-2011")` 
`=MONTH("28-Feb-2011")`
`=MONTH("28-Фев-2011")`
`=MONTH("28-february-2011")`
`=MONTH("28 february 2011")`
`=MONTH("28 февраль 2011")`
`=MONTH("2011.02.28")` 
`=MONTH("2011-02-28")`
`=MONTH(40602)`

You should support all of them

2021-11-10 09:41 UTC, ulalka commented on tests/test_rpn/test_functions.py
> +    for excel_function in ('MONTH', 'YEAR'):
omg, use `pytest.mark.parametrize`

2021-11-10 09:41 UTC, ulalka commented on efc/rpn_builder/parser/functions.py
> +            except:
Handle exception may be slower than using `if` statement. Please, check it and use faster solution.

2021-11-16 13:33 UTC, closed without merging

2021-11-16 13:34 UTC, AntonArsentiev commented
closing pull-request without comments